import express from 'express';
import { PrismaClient } from '@prisma/client';
import { getCookie, tokenHash } from './auth.js';

const prisma = new PrismaClient();
const originalListen = express.application.listen;
let registered = false;

const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money = v => Number(v || 0).toFixed(2);
const orderNumber = () => `BILL-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;

async function userFrom(req){
  const token=getCookie(req,'rp_session');
  if(!token)return null;
  const s=await prisma.session.findUnique({where:{tokenHash:tokenHash(token)},include:{user:true}}).catch(()=>null);
  if(!s||s.expiresAt<new Date())return null;
  return s.user;
}

async function access(req,businessId){
  const user=await userFrom(req);
  if(!user)return {status:401,error:'Authentication required'};
  const business=await prisma.business.findFirst({where:{id:String(businessId),...(['ADMIN','SUPER_ADMIN'].includes(user.role)?{}:{members:{some:{userId:user.id}}})},select:{id:true,name:true,type:true,phone:true}});
  if(!business)return {status:403,error:'Business access denied'};
  return {user,business};
}

async function billingMeta(orderId){
  const row=await prisma.auditLog.findFirst({where:{entity:'Order',entityId:orderId,action:'BILL_CREATED'},orderBy:{createdAt:'desc'}}).catch(()=>null);
  return row?.metadata && typeof row.metadata==='object' ? row.metadata : null;
}

async function createBillingLog(userId,order,meta){
  return prisma.auditLog.create({data:{actorUserId:userId,action:'BILL_CREATED',entity:'Order',entityId:order.id,metadata:{...meta,billNumber:order.orderNumber}}});
}

function invoicePage(business,order,meta){
  const subtotal=Number(meta?.subtotal ?? order.items.reduce((s,i)=>s+Number(i.lineTotal||0),0));
  const discount=Number(meta?.discount||0);const taxRate=Number(meta?.taxRate||0);const tax=Number(meta?.tax||0);const total=Number(order.total||0);
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Invoice ${esc(order.orderNumber)}</title><style>*{box-sizing:border-box}body{margin:0;background:#f3f4f6;color:#111827;font-family:Arial,sans-serif}.paper{width:min(760px,100%);margin:20px auto;background:#fff;padding:32px;border:1px solid #e5e7eb}.head{display:flex;justify-content:space-between;gap:20px;border-bottom:2px solid #111827;padding-bottom:18px}.brand{font-size:25px;font-weight:800}.muted{color:#667085;font-size:12px}.bill{text-align:right}.items{margin-top:22px}.line{display:grid;grid-template-columns:1fr 80px 110px 110px;gap:10px;padding:10px 0;border-bottom:1px solid #eee}.line b{text-align:right}.totals{margin-left:auto;width:min(360px,100%);margin-top:18px}.total{display:flex;justify-content:space-between;padding:7px 0}.grand{font-size:20px;font-weight:800;border-top:2px solid #111827;margin-top:5px;padding-top:10px}.actions{margin-top:24px;display:flex;gap:10px}.btn{border:0;border-radius:9px;padding:11px 16px;font-weight:700;cursor:pointer;background:#111827;color:#fff}.btn.secondary{background:#fff;color:#111827;border:1px solid #d1d5db}@media print{body{background:#fff}.paper{border:0;margin:0;padding:15px}.actions{display:none}}@media(max-width:560px){.paper{padding:18px}.head{flex-direction:column}.bill{text-align:left}.line{grid-template-columns:1fr 55px 85px 85px;font-size:12px}}
</style></head><body><main class="paper"><header class="head"><div><div class="brand">${esc(business.name)}</div><div class="muted">${esc(business.phone||'')} </div><div class="muted">GST / Tax invoice</div></div><div class="bill"><b>Bill #${esc(order.orderNumber)}</b><div class="muted">${new Date(order.createdAt).toLocaleString('en-IN')}</div><div class="muted">Payment: ${esc(order.paymentMethod||'MANUAL')} · ${esc(order.paymentStatus||'UNPAID')}</div></div></header><section style="margin-top:18px"><b>Customer</b><div>${esc(order.customerName||'Walk-in Customer')}</div><div class="muted">${esc(order.customerPhone||'')}</div></section><section class="items"><div class="line"><b>Item</b><b>Qty</b><b>Rate</b><b>Amount</b></div>${order.items.map(i=>`<div class="line"><span>${esc(i.itemName)}</span><span>${i.quantity}</span><span>₹${money(i.unitPrice)}</span><b>₹${money(i.lineTotal)}</b></div>`).join('')}</section><section class="totals"><div class="total"><span>Subtotal</span><b>₹${money(subtotal)}</b></div><div class="total"><span>Discount</span><b>- ₹${money(discount)}</b></div><div class="total"><span>GST / Tax (${money(taxRate)}%)</span><b>₹${money(tax)}</b></div><div class="total grand"><span>Total</span><b>₹${money(total)}</b></div></section><div class="muted" style="margin-top:18px">Thank you for your business.</div><div class="actions"><button class="btn" onclick="window.print()">Print / Save PDF</button><button class="btn secondary" onclick="history.back()">Back</button></div></main></body></html>`;
}

const page=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Billing & POS | Repute-Tech</title><style>*{box-sizing:border-box}body{margin:0;background:#f5f7fb;color:#172033;font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif}.wrap{max-width:1240px;margin:auto;padding:22px}.hero{background:linear-gradient(135deg,#10182f,#303b6d);color:#fff;border-radius:22px;padding:22px;display:flex;justify-content:space-between;gap:16px;align-items:center}.brand{font-size:26px;font-weight:850}.muted{font-size:13px;color:#748096}.hero .muted{color:#c2c9d8}.layout{display:grid;grid-template-columns:1.2fr .8fr;gap:15px;margin-top:15px}.card{background:#fff;border:1px solid #e6e9f0;border-radius:17px;padding:17px;box-shadow:0 7px 22px rgba(30,42,70,.05)}.title{font-size:17px;font-weight:800}.sub{font-size:13px;color:#748096;line-height:1.45}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:12px}.product{border:1px solid #e5e7eb;border-radius:14px;padding:13px;background:#fff;cursor:pointer}.product:hover{border-color:#5b4be7}.product b{display:block}.price{font-weight:800;margin-top:7px}.qty{font-size:12px;color:#5b4be7;margin-top:5px}.cart{display:grid;gap:9px;margin-top:12px}.cartrow{display:flex;justify-content:space-between;gap:10px;padding:10px 0;border-bottom:1px solid #edf0f4}.field{width:100%;padding:11px;border:1px solid #dfe3eb;border-radius:10px;font:inherit;margin-top:9px}.row{display:flex;gap:9px;align-items:center;justify-content:space-between}.summary{display:grid;gap:7px;margin-top:15px}.sum{display:flex;justify-content:space-between}.grand{font-size:21px;font-weight:850;border-top:2px solid #172033;padding-top:10px;margin-top:4px}.btn{border:0;border-radius:10px;padding:11px 14px;background:#5b4be7;color:#fff;font-weight:800;cursor:pointer}.btn.secondary{background:#fff;color:#172033;border:1px solid #dfe3eb}.btn:disabled{opacity:.55}.tabs{display:flex;gap:8px;overflow:auto;margin-top:15px}.tab{border:1px solid #dfe3eb;background:#fff;border-radius:999px;padding:9px 13px;font-weight:700;cursor:pointer;white-space:nowrap}.tab.active{background:#172033;color:#fff}.history{display:grid;gap:9px;margin-top:12px}.billrow{border:1px solid #e6e9f0;border-radius:13px;padding:13px;background:#fff}.billrow .actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.pill{font-size:11px;padding:4px 8px;border-radius:999px;background:#ecfdf3;color:#15803d;font-weight:700}.notice{padding:10px;border-radius:10px;background:#f8fafc;color:#667085;font-size:12px;margin-top:10px}.error{color:#b42318;font-size:13px;margin-top:8px}@media(max-width:900px){.layout{grid-template-columns:1fr}.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.wrap{padding:12px}.hero{padding:18px;border-radius:17px;align-items:flex-start;flex-direction:column}.brand{font-size:22px}.grid{grid-template-columns:1fr 1fr}.card{padding:14px}}
</style></head><body><div class="wrap"><div class="hero"><div><div class="brand">Billing & POS</div><div class="muted" id="business">Loading business…</div></div><button class="btn secondary" onclick="location.href='/'">Dashboard</button></div><div class="layout"><section class="card"><div class="title">Create bill</div><div class="sub">Select menu items, apply discount/GST, then collect cash, UPI or card.</div><div id="products" class="grid"></div></section><aside class="card"><div class="title">Current bill</div><div id="cart" class="cart"><div class="sub">Add items from the left.</div></div><input id="customerName" class="field" value="Walk-in Customer" placeholder="Customer name"><input id="customerPhone" class="field" placeholder="Phone number (optional)"><input id="discount" class="field" type="number" min="0" step="0.01" placeholder="Discount ₹"><input id="taxRate" class="field" type="number" min="0" max="100" step="0.01" value="0" placeholder="GST / Tax %"><select id="payment" class="field"><option value="CASH">Cash</option><option value="UPI">UPI</option><option value="CARD">Card</option></select><div id="summary" class="summary"></div><button id="complete" class="btn" style="width:100%;margin-top:13px">Complete bill & mark paid</button><div id="msg" class="error"></div></aside></div><div class="card" style="margin-top:15px"><div class="row"><div><div class="title">Bill history</div><div class="sub">Recent bills and payment status.</div></div><button id="reload" class="btn secondary">Reload</button></div><div class="tabs"><button class="tab active" data-filter="ALL">All</button><button class="tab" data-filter="PAID">Paid</button><button class="tab" data-filter="UNPAID">Unpaid</button></div><div id="history" class="history"></div></div><div class="card" style="margin-top:15px"><div class="title">Daily sales closing</div><div id="daily" class="sub">Loading today’s sales…</div><button id="closeDay" class="btn" style="margin-top:10px">Close today</button><div class="notice">Closing records the current day’s sales summary. It does not delete or alter orders.</div></div></div><script>
let businessId=null,menus=[],cart=new Map(),filter='ALL';const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const money=n=>Number(n||0).toFixed(2);async function req(url,opt={}){const r=await fetch(url,{credentials:'include',headers:{'content-type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
async function init(){try{const bs=await req('/api/businesses');const b=bs[0];if(!b)throw new Error('No business found');businessId=b.id;$('business').textContent=b.name;menus=await req('/api/businesses/'+encodeURIComponent(businessId)+'/billing/menu');renderProducts();renderCart();loadHistory();loadDaily()}catch(e){$('msg').textContent=e.message}}
function renderProducts(){const items=menus.flatMap(m=>m.items||[]);$('products').innerHTML=items.length?items.map(i=>'<button class="product" data-id="'+esc(i.id)+'"><b>'+esc(i.name)+'</b><span class="muted">'+esc(i.menuName||'')+'</span><div class="price">₹'+money(i.price)+'</div><div class="qty">Add to bill</div></button>').join(''):'<div class="sub">No published menu items found.</div>'}
$('products').onclick=e=>{const b=e.target.closest('[data-id]');if(!b)return;const id=b.dataset.id;cart.set(id,(cart.get(id)||0)+1);renderCart()};
function totals(){let subtotal=0;for(const [id,q]of cart){const i=menus.flatMap(m=>m.items||[]).find(x=>x.id===id);if(i)subtotal+=Number(i.price)*q}const discount=Math.max(0,Number($('discount').value||0));const base=Math.max(0,subtotal-discount);const taxRate=Math.min(100,Math.max(0,Number($('taxRate').value||0)));const tax=base*taxRate/100;return {subtotal,discount,taxRate,tax,total:base+tax}}
function renderCart(){let html='';for(const [id,q]of cart){const i=menus.flatMap(m=>m.items||[]).find(x=>x.id===id);if(i)html+='<div class="cartrow"><span>'+esc(i.name)+' × '+q+'</span><b>₹'+money(Number(i.price)*q)+'</b></div>'}$('cart').innerHTML=html||'<div class="sub">Add items from the left.</div>';const t=totals();$('summary').innerHTML='<div class="sum"><span>Subtotal</span><b>₹'+money(t.subtotal)+'</b></div><div class="sum"><span>Discount</span><b>- ₹'+money(t.discount)+'</b></div><div class="sum"><span>GST / Tax ('+money(t.taxRate)+'%)</span><b>₹'+money(t.tax)+'</b></div><div class="sum grand"><span>Total</span><b>₹'+money(t.total)+'</b></div>'}
$('discount').oninput=renderCart;$('taxRate').oninput=renderCart;
async function loadHistory(){try{const rows=await req('/api/businesses/'+encodeURIComponent(businessId)+'/billing/history?filter='+filter);$('history').innerHTML=rows.length?rows.map(o=>'<div class="billrow"><div class="row"><b>'+esc(o.orderNumber)+'</b><span class="pill">'+esc(o.paymentStatus)+'</span></div><div class="sub" style="margin-top:5px">'+esc(o.customerName)+' · '+new Date(o.createdAt).toLocaleString('en-IN')+' · '+esc(o.paymentMethod||'MANUAL')+'</div><div style="margin-top:7px;font-size:19px;font-weight:800">₹'+money(o.total)+'</div><div class="actions"><a class="btn secondary" href="/billing-pos/invoice/'+encodeURIComponent(o.id)+'" target="_blank">Invoice</a>'+(o.paymentStatus!=='PAID'?'<button class="btn" data-settle="'+esc(o.id)+'">Mark paid</button>':'')+'</div></div>').join(''):'<div class="sub">No bills found.</div>'}catch(e){$('history').innerHTML='<div class="error">'+esc(e.message)+'</div>'}}
$('history').onclick=async e=>{const b=e.target.closest('[data-settle]');if(!b)return;try{b.disabled=true;await req('/api/businesses/'+encodeURIComponent(businessId)+'/billing/settle/'+encodeURIComponent(b.dataset.settle),{method:'POST',body:JSON.stringify({paymentMethod:'CASH'})});loadHistory();loadDaily()}catch(e){alert(e.message)}};
async function loadDaily(){try{const d=await req('/api/businesses/'+encodeURIComponent(businessId)+'/billing/daily');$('daily').textContent='Today: '+d.paidBills+' paid bills · ₹'+money(d.revenue)+' revenue · Cash ₹'+money(d.cash)+' · UPI ₹'+money(d.upi)+' · Card ₹'+money(d.card)+(d.closed?' · Day closed at '+new Date(d.closedAt).toLocaleString('en-IN'):' · Not closed yet')}catch(e){$('daily').textContent=e.message}}
$('complete').onclick=async()=>{const items=[...cart.entries()].filter(([,q])=>q>0).map(([menuItemId,quantity])=>({menuItemId,quantity}));if(!items.length){$('msg').textContent='Add at least one item.';return}const t=totals();if(t.discount>t.subtotal){$('msg').textContent='Discount cannot exceed subtotal.';return}$('msg').textContent='';const btn=$('complete');btn.disabled=true;btn.textContent='Saving bill…';try{const o=await req('/api/businesses/'+encodeURIComponent(businessId)+'/billing/bills',{method:'POST',body:JSON.stringify({customerName:$('customerName').value.trim()||'Walk-in Customer',customerPhone:$('customerPhone').value.trim()||null,items,discount:t.discount,taxRate:t.taxRate,paymentMethod:$('payment').value})});cart.clear();renderCart();await loadHistory();await loadDaily();window.open('/billing-pos/invoice/'+encodeURIComponent(o.order.id),'_blank')}catch(e){$('msg').textContent=e.message}finally{btn.disabled=false;btn.textContent='Complete bill & mark paid'}};
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;loadHistory()});$('reload').onclick=()=>{loadHistory();loadDaily()};$('closeDay').onclick=async()=>{try{const d=await req('/api/businesses/'+encodeURIComponent(businessId)+'/billing/close-day',{method:'POST'});$('daily').textContent='Today closed at '+new Date(d.closedAt).toLocaleString('en-IN')+' · '+d.paidBills+' paid bills · ₹'+money(d.revenue)}catch(e){alert(e.message)}};init();
</script></body></html>`;

function register(app){if(registered)return;registered=true;
  app.get('/billing-pos',async(req,res,next)=>{try{
    const u=await userFrom(req);if(!u)return res.redirect('/');
    const business=await prisma.business.findFirst({where:{members:{some:{userId:u.id}}},select:{id:true}});
    if(!business)return res.status(403).send('Business access denied');
    if(!['ADMIN','SUPER_ADMIN','OWNER'].includes(String(u.role||'').toUpperCase())){
      const member=await prisma.businessMember.findFirst({where:{userId:u.id,businessId:business.id},select:{permissions:true}});
      const permissions=member?.permissions&&typeof member.permissions==='object'?member.permissions:{};
      if(permissions.BILLING!==true)return res.status(403).send('Billing & POS access has not been granted by the business owner.');
    }
    res.set('Cache-Control','no-store');res.type('html').send(page)
  }catch(e){next(e)}});
  app.get('/api/businesses/:businessId/billing/menu',async(req,res,next)=>{try{const a=await access(req,req.params.businessId);if(a.error)return res.status(a.status).json({error:a.error});const menus=await prisma.menu.findMany({where:{businessId:a.business.id,isPublished:true},orderBy:{createdAt:'desc'},include:{items:{where:{available:true},orderBy:{name:'asc'}}}});res.json(menus.map(m=>({id:m.id,name:m.name,items:m.items.map(i=>({id:i.id,name:i.name,price:Number(i.price),category:i.category||'',menuName:m.name}))})))}catch(e){next(e)}});
  app.get('/api/businesses/:businessId/billing/history',async(req,res,next)=>{try{const a=await access(req,req.params.businessId);if(a.error)return res.status(a.status).json({error:a.error});const filter=String(req.query.filter||'ALL');const where={businessId:a.business.id,...(filter==='PAID'?{paymentStatus:'PAID'}:filter==='UNPAID'?{paymentStatus:'UNPAID'}:{})};const orders=await prisma.order.findMany({where,include:{items:true},orderBy:{createdAt:'desc'},take:100});res.json(orders)}catch(e){next(e)}});
  app.get('/api/businesses/:businessId/billing/daily',async(req,res,next)=>{try{const a=await access(req,req.params.businessId);if(a.error)return res.status(a.status).json({error:a.error});const start=new Date();start.setHours(0,0,0,0);const orders=await prisma.order.findMany({where:{businessId:a.business.id,createdAt:{gte:start},paymentStatus:'PAID'},select:{total:true,paymentMethod:true}});const revenue=orders.reduce((s,o)=>s+Number(o.total||0),0);const sums={CASH:0,UPI:0,CARD:0};for(const o of orders){if(sums[o.paymentMethod]!=null)sums[o.paymentMethod]+=Number(o.total||0)}const close=await prisma.auditLog.findFirst({where:{businessId:undefined,action:'BILLING_DAY_CLOSED',entity:'Business',entityId:a.business.id,createdAt:{gte:start}},orderBy:{createdAt:'desc'}}).catch(()=>null);res.json({paidBills:orders.length,revenue,cash:sums.CASH,upi:sums.UPI,card:sums.CARD,closed:!!close,closedAt:close?.createdAt||null})}catch(e){next(e)}});
  app.post('/api/businesses/:businessId/billing/bills',async(req,res,next)=>{try{const a=await access(req,req.params.businessId);if(a.error)return res.status(a.status).json({error:a.error});const b=req.body||{};const name=String(b.customerName||'Walk-in Customer').trim().slice(0,80)||'Walk-in Customer';const phone=String(b.customerPhone||'').trim()||null;const raw=Array.isArray(b.items)?b.items:[];if(!raw.length)return res.status(400).json({error:'At least one item is required'});const menus=await prisma.menu.findMany({where:{businessId:a.business.id,isPublished:true},include:{items:true}});const map=new Map(menus.flatMap(m=>m.items.filter(i=>i.available).map(i=>[i.id,i])));const chosen=[];for(const x of raw){const id=String(x?.menuItemId||''),q=Math.floor(Number(x?.quantity));const item=map.get(id);if(item&&q>0&&q<=100)chosen.push({item,q})}if(!chosen.length)return res.status(400).json({error:'No valid available items selected'});const items=chosen.map(({item,q})=>{const unit=Number(item.price);return {menuItemId:item.id,itemName:item.name,quantity:q,unitPrice:unit,lineTotal:Number((unit*q).toFixed(2))}});const subtotal=items.reduce((s,i)=>s+i.lineTotal,0);const discount=Math.max(0,Number(b.discount||0));const taxRate=Math.min(100,Math.max(0,Number(b.taxRate||0)));if(discount>subtotal)return res.status(400).json({error:'Discount cannot exceed subtotal'});const base=subtotal-discount;const tax=Number((base*taxRate/100).toFixed(2));const total=Number((base+tax).toFixed(2));const method=['CASH','UPI','CARD'].includes(String(b.paymentMethod||''))?String(b.paymentMethod):'CASH';let customer=phone?await prisma.customer.findFirst({where:{businessId:a.business.id,phone}}):null;if(!customer)customer=await prisma.customer.create({data:{businessId:a.business.id,name,phone,lastInteractionAt:new Date()}});else await prisma.customer.update({where:{id:customer.id},data:{name,lastInteractionAt:new Date()}});const order=await prisma.order.create({data:{businessId:a.business.id,menuId:menus[0]?.id||null,customerId:customer.id,orderNumber:orderNumber(),customerName:name,customerPhone:phone,fulfilmentType:'IN_STORE',status:'ACCEPTED',paymentStatus:'PAID',paymentMethod:method,notes:null,total,items:{create:items}},include:{items:true}});await createBillingLog(a.user.id,order,{subtotal:Number(subtotal.toFixed(2)),discount:Number(discount.toFixed(2)),taxRate:Number(taxRate.toFixed(2)),tax,total,paymentMethod:method,source:'POS'});await prisma.customerInteraction.create({data:{customerId:customer.id,type:'POS_BILL',channel:'POS',metadata:{orderId:order.id,orderNumber:order.orderNumber,total}}}).catch(()=>{});res.status(201).json({ok:true,order})}catch(e){next(e)}});
  app.post('/api/businesses/:businessId/billing/settle/:orderId',async(req,res,next)=>{try{const a=await access(req,req.params.businessId);if(a.error)return res.status(a.status).json({error:a.error});const order=await prisma.order.findFirst({where:{id:req.params.orderId,businessId:a.business.id},include:{items:true}});if(!order)return res.status(404).json({error:'Bill not found'});const method=['CASH','UPI','CARD'].includes(String(req.body?.paymentMethod||''))?String(req.body.paymentMethod):'CASH';const updated=await prisma.order.update({where:{id:order.id},data:{paymentStatus:'PAID',paymentMethod:method,status:order.status==='CANCELLED'?'CANCELLED':'ACCEPTED'},include:{items:true}});const old=await billingMeta(order.id);await createBillingLog(a.user.id,updated,{...(old||{}),paymentMethod:method,source:old?.source||'ORDER_SETTLEMENT'});res.json({ok:true,order:updated})}catch(e){next(e)}});
  app.get('/billing-pos/invoice/:orderId',async(req,res,next)=>{try{const u=await userFrom(req);if(!u)return res.status(401).send('Authentication required');const order=await prisma.order.findUnique({where:{id:req.params.orderId},include:{items:true,business:true}});if(!order)return res.status(404).send('Bill not found');const a=await access(req,order.businessId);if(a.error)return res.status(a.status).send(a.error);const meta=await billingMeta(order.id)||{subtotal:order.items.reduce((s,i)=>s+Number(i.lineTotal||0),0),discount:0,taxRate:0,tax:0};res.type('html').send(invoicePage(order.business,order,meta))}catch(e){next(e)}});
  app.post('/api/businesses/:businessId/billing/close-day',async(req,res,next)=>{try{const a=await access(req,req.params.businessId);if(a.error)return res.status(a.status).json({error:a.error});const start=new Date();start.setHours(0,0,0,0);const orders=await prisma.order.findMany({where:{businessId:a.business.id,createdAt:{gte:start},paymentStatus:'PAID'},select:{total:true}});const revenue=orders.reduce((s,o)=>s+Number(o.total||0),0);const row=await prisma.auditLog.create({data:{actorUserId:a.user.id,action:'BILLING_DAY_CLOSED',entity:'Business',entityId:a.business.id,metadata:{paidBills:orders.length,revenue:Number(revenue.toFixed(2)),date:start.toISOString().slice(0,10)}}});res.json({ok:true,closedAt:row.createdAt,paidBills:orders.length,revenue})}catch(e){next(e)}});
}

express.application.listen=function billingPosListen(...args){register(this);return originalListen.apply(this,args)};
