(function(){
  const $=id=>document.getElementById(id);
  const api=async(url,opt={})=>{const r=await fetch('/api'+url,{credentials:'include',headers:{'content-type':'application/json',...(opt.headers||{})},...opt});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed');return j};
  function addNav(){const side=document.querySelector('.side')||document.querySelector('.nav');if(side&&!side.querySelector('[data-page="orders"]')){const b=document.createElement('button');b.type='button';b.dataset.page='orders';b.textContent='▤ Orders';const a=side.querySelector('[data-page="pricing"]');side.insertBefore(b,a||null);b.addEventListener('click',showOrders)}const bar=document.querySelector('.mobilebar');if(bar&&!bar.querySelector('[data-page="orders"]')){const b=document.createElement('button');b.type='button';b.dataset.page='orders';b.textContent='▤ Orders';b.style.minWidth='94px';b.addEventListener('click',showOrders);bar.appendChild(b)}}
  function addSection(){if($('orders'))return;const main=document.querySelector('main.main');if(!main)return;const s=document.createElement('section');s.id='orders';s.className='page';s.innerHTML='<div class="card"><div class="row" style="justify-content:space-between"><div><div class="section-title">Digital Menu Orders</div><div class="sub">Manage customer orders. Available statuses: Pending, Accepted, Cancelled.</div></div><button class="btn secondary" id="reloadOrders" type="button">Reload</button></div><div id="orderSummary" class="grid" style="grid-template-columns:repeat(3,1fr);margin:14px 0"></div><div id="ordersList" class="list"></div></div>';main.appendChild(s);$('reloadOrders').addEventListener('click',loadOrders)}
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const money=n=>'₹'+Number(n||0).toFixed(2);
  function updateBadge(n){['ordersBadge','ordersBadgeMobile'].forEach(id=>{const e=$(id);if(e){e.textContent=n;e.style.display=n?'inline-block':'none'}})}
  async function loadOrders(){addNav();addSection();const list=$('ordersList');if(!list)return;list.innerHTML='<div class="sub">Loading orders…</div>';try{const bs=await api('/businesses');const b=bs[0];if(!b){list.innerHTML='<div class="sub">No business found.</div>';return}const orders=await api('/businesses/'+encodeURIComponent(b.id)+'/orders');const counts={PENDING:0,ACCEPTED:0,CANCELLED:0};orders.forEach(o=>counts[o.status]=(counts[o.status]||0)+1);updateBadge(counts.PENDING);$('orderSummary').innerHTML='<div class="card"><div class="label">Pending</div><div class="value">'+counts.PENDING+'</div></div><div class="card"><div class="label">Accepted</div><div class="value">'+counts.ACCEPTED+'</div></div><div class="card"><div class="label">Cancelled</div><div class="value">'+counts.CANCELLED+'</div></div>';if(!orders.length){list.innerHTML='<div class="sub">No orders yet. Orders from the published digital menu will appear here.</div>';return}list.innerHTML='';orders.forEach(o=>{const item=document.createElement('div');item.className='item';const head=document.createElement('div');head.innerHTML='<strong>'+esc(o.orderNumber)+'</strong> · <b>'+esc(o.status)+'</b><div class="sub" style="margin-top:6px">'+esc(o.customerName)+(o.customerPhone?' · '+esc(o.customerPhone):'')+'</div><div style="margin-top:10px">'+(o.items||[]).map(i=>esc(i.itemName)+' × '+Number(i.quantity||0)+' — '+money(i.lineTotal)).join('<br>')+'</div><div class="sub" style="margin-top:8px">'+new Date(o.createdAt).toLocaleString()+(o.notes?' · '+esc(o.notes):'')+'</div><div style="text-align:right;margin-top:8px"><b style="font-size:20px">'+money(o.total)+'</b><div class="sub">Pay at store</div></div>';item.appendChild(head);const actions=document.createElement('div');actions.style='display:flex;gap:8px;flex-wrap:wrap;margin-top:13px';['PENDING','ACCEPTED','CANCELLED'].forEach(st=>{const btn=document.createElement('button');btn.type='button';btn.className='btn '+(st==='ACCEPTED'?'':'secondary');btn.textContent=st;btn.disabled=o.status===st;btn.onclick=()=>updateOrderStatus(o.id,st);actions.appendChild(btn)});item.appendChild(actions);list.appendChild(item)})}catch(e){list.innerHTML='<div class="sub">'+esc(e.message)+'</div>'}}
  async function updateOrderStatus(id,status){if(status==='CANCELLED'&&!confirm('Cancel this order?'))return;try{await api('/orders/'+encodeURIComponent(id)+'/status',{method:'PATCH',body:JSON.stringify({status})});await loadOrders()}catch(e){alert(e.message)}}
  function showOrders(){addNav();addSection();document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$('orders').classList.add('active');document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page==='orders'));if($('heading'))$('heading').textContent='Orders';loadOrders()}
  window.showOrders=showOrders;window.updateOrderStatus=updateOrderStatus;
  function boot(){addNav();addSection();setTimeout(()=>loadOrders(),700);setInterval(addNav,3000);setInterval(()=>{if($('orders')?.classList.contains('active'))loadOrders()},15000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();