(function(){
  const $=id=>document.getElementById(id);
  const api=async(url,opt={})=>{const r=await fetch('/api'+url,{headers:{'content-type':'application/json',...(opt.headers||{})},...opt});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed');return j};
  function addNav(){if(document.querySelector('[data-page="orders"]'))return;const side=document.querySelector('.nav');if(side){const b=document.createElement('button');b.dataset.page='orders';b.textContent='▤ Orders';side.insertBefore(b,side.querySelector('[data-page="pricing"]'));b.onclick=showOrders}const bar=document.querySelector('.mobilebar');if(bar){const b=document.createElement('button');b.dataset.page='orders';b.textContent='▤ Orders';bar.insertBefore(b,bar.querySelector('[data-page="pricing"]'));b.onclick=showOrders}}
  function addSection(){if($('orders'))return;const main=document.querySelector('main.main');if(!main)return;const s=document.createElement('section');s.id='orders';s.className='page';s.innerHTML='<div class="card"><div class="row" style="justify-content:space-between"><div><div class="section-title">Digital Menu Orders</div><div class="sub">Customer orders appear here instantly. Payment is collected manually in the store.</div></div><button class="btn secondary" id="reloadOrders">Reload</button></div><div id="orderSummary" class="grid" style="grid-template-columns:repeat(3,1fr);margin:14px 0"></div><div id="ordersList" class="list"></div></div>';main.appendChild(s);$('reloadOrders').onclick=loadOrders}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
  function money(n){return '₹'+Number(n||0).toFixed(2)}
  function badge(status){const cls=status==='ACCEPTED'?'style="background:#ecfdf3;color:#15803d"':status==='CANCELLED'?'style="background:#fef2f2;color:#b91c1c"':'style="background:#fff7ed;color:#c2410c"';return '<span class="pill" '+cls+'>'+esc(status)+'</span>'}
  async function loadOrders(){addSection();const list=$('ordersList');list.innerHTML='<div class="sub">Loading orders…</div>';try{const r=await fetch('/api/businesses');const bs=await r.json();const b=bs[0];if(!b){list.innerHTML='<div class="sub">No business found.</div>';return}const orders=await api('/businesses/'+encodeURIComponent(b.id)+'/orders');const pending=orders.filter(o=>o.status==='PENDING').length,accepted=orders.filter(o=>o.status==='ACCEPTED').length,cancelled=orders.filter(o=>o.status==='CANCELLED').length;$('orderSummary').innerHTML='<div class="card"><div class="label">Pending</div><div class="value">'+pending+'</div></div><div class="card"><div class="label">Accepted</div><div class="value">'+accepted+'</div></div><div class="card"><div class="label">Cancelled</div><div class="value">'+cancelled+'</div></div>';if(!orders.length){list.innerHTML='<div class="sub">No orders yet. Orders from your published digital menu will appear here.</div>';return}list.innerHTML=orders.map(o=>'<div class="item"><div class="row" style="justify-content:space-between;align-items:flex-start;gap:14px"><div style="min-width:0"><strong>'+esc(o.orderNumber)+'</strong> '+badge(o.status)+'<div class="sub" style="margin-top:6px">'+esc(o.customerName)+(o.customerPhone?' · '+esc(o.customerPhone):'')+'</div><div style="margin-top:10px">'+o.items.map(i=>esc(i.itemName)+' × '+i.quantity+' — '+money(i.lineTotal)).join('<br>')+'</div><div class="sub" style="margin-top:8px">'+new Date(o.createdAt).toLocaleString()+(o.notes?' · '+esc(o.notes):'')+'</div></div><div style="text-align:right;white-space:nowrap"><div class="value" style="font-size:20px">'+money(o.total)+'</div><div class="sub">'+(o.paymentStatus==='PAID'?'Payment received manually':'Pay at store')+'</div></div></div><div class="row" style="margin-top:13px;flex-wrap:wrap">'+['PENDING','ACCEPTED','CANCELLED'].map(st=>'<button class="btn '+(st==='ACCEPTED'?'':'secondary')+'" style="padding:7px 10px;font-size:11px" onclick="window.updateOrderStatus(\\''+o.id+'\\',\\''+st+'\\')" '+(o.status===st?'disabled':'')+'>'+st+'</button>').join('')+'</div></div>').join('')}catch(e){list.innerHTML='<div class="sub">'+esc(e.message)+'</div>'}}
  window.updateOrderStatus=async(id,status)=>{if(status==='CANCELLED'&&!confirm('Cancel this order?'))return;try{await api('/orders/'+encodeURIComponent(id)+'/status',{method:'PATCH',body:JSON.stringify({status})});const t=$('toast');if(t){t.textContent='Order updated';t.style.display='block';setTimeout(()=>t.style.display='none',2200)}loadOrders()}catch(e){const t=$('toast');if(t){t.textContent=e.message;t.style.display='block';setTimeout(()=>t.style.display='none',2500)}}};
  function showOrders(){addSection();document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$('orders').classList.add('active');document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page==='orders'));if($('heading'))$('heading').textContent='Orders';loadOrders()}
  function boot(){addNav();addSection()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
